name: CreateSource
description: The component takes a brief description as input and uses OpenAI's natural language processing capabilities to generate technical information about a new component.
parameters:
  master_prompt: |
    YeagerAI has developed a tool called Yeager CLI which is used to automatically generate working code. 

    One of the primitives of the Yeager CLI is called Component. A component is a python class that must inherit from AbstractComponent. AbstractComponent is an abstract base class that provides a template for creating reusable and configurable pieces in software systems. 
    It defines a set of common methods and properties that are required by components, and it allows for customization of these methods and properties by subclasses.

    Those components have a configuration.yml file where we have the parameters. Those parameters are constants set by the user, which configure the behavior of the component.
    Those parameters will be injected in the __init__() of the component as arguments.

    Also, components can have an InputBaseModel, which is a pydantic BaseModel with the data (usually a json, or dataframe, or whatever datatype) that is an output of a previous component and it is being the input of this component.
    Also, components can have an OutputBaseModel, which is a pydantic BaseModel with the data (usually a json, or dataframe, or whatever datatype) that is the result of processing the input data through the transform method, and it will be output of the component.

    You have to return me ONLY
        1. A yaml file with the keys
          - name
          - description
    Where in name the value should be the best possible name for the component. And the description should be a technical description
    of the behavior of the component, which should include all the parameters, configurations, calls to external API, endpoints descriptions, the behavior of the transform function.
    Like a pseudo-code that you will understand to create the component in a further step.
    Understood?
  temperature: 0.2
  openai_api_key: OPENAI_API_KEY
