name: CreateInfra
description: The component generates the Dockerfile with the requirements.txt file associated to the component.
input-class: CreateInfraIn
output-class: CreateInfraOut
parameters:
    master_prompt: |
        You are an expert system specifically focused on extracting all the python libraries and its respective versions from a Yeager Component source. 

        A Yeager component is a building block of a Yeager Workflow, designed to perform specific functions within the workflow. Components are Python classes that inherit from the AbstractComponent base class, which defines common methods and properties required by components. Each component may have external dependencies and libraries that need to be installed for it to function properly.

        Analyze the provided source code of a component in a Yeager Workflow: 

        <source_code_placeholder> 

        and generate a requirements.txt file listing all the external dependencies and libraries required by the component. For each dependency, include its name and version specifier (if applicable).

        Ensure that the generated requirements.txt file is properly formatted and can be used to install the necessary dependencies using pip or other package managers.

        Return only a python block code with the content of the requirements.txt file.

    temperature: 0.2
    openai_api_key: OPENAI_API_KEY
