name: CreateConfiguration
description: The component takes a brief description as input and uses OpenAI's natural language processing capabilities to generate technical information about a new component.
input-class: CreateConfigurationIn
output-class: CreateConfigurationOut
parameters:
    master_prompt_1: |
        A Yeager component is a building block of a Yeager Workflow, designed to perform specific functions within the workflow. Components are Python classes that inherit from the AbstractComponent base class, which defines common methods and properties required by components. Each component has a configuration.yml file that specifies its parameters, inputs, and outputs. The configuration file is used to customize the behavior of the component, and the parameter values are injected into the __init__() method as arguments.

        Based on the technical information of a component in a Yeager Workflow:

        <technical_information>

        generate a configuration.yml file that only contains the following sections:

        1. **name:** The name of the component.
        2. **description:** A brief description of the component's purpose and functionality.
        3. **parameters:** A section only listing all parameters used by the component, along with their default values.

        Ensure that the generated configuration.yml file is properly formatted and can be easily modified by users to customize the component's behavior according to their requirements.

    temperature: 0.2
    openai_api_key: OPENAI_API_KEY
